# Generated by Django 3.2.9 on 2021-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
